### ISSUE TITLE
Unable to build/compile (SettingsN.hpp not found)

### ISSUE THREAD

**Issue by muzy** [Consti10/Telemetry#3]
Hi,

I am unable to compile the TelemetryCore (as well as the FPV_VR_OS) project since the **SettingsN.hpp** file is not included within the git sources (with current source at commit 3bbfd9b7d591a22312d06a494bdf22c90026b674)

The gradle task **:app:externalNativeBuildDebug** yields the following error:

```
In file included from /home/build/git/Telemetry/TelemetryCore/src/main/cpp/TelemetryReceiver/TelemetryReceiver.cpp:5:
/home/build/git/Telemetry/TelemetryCore/src/main/cpp/TelemetryReceiver/TelemetryReceiver.h:17:10: fatal error: 'SettingsN.hpp' file not found
In file included from /home/build/git/FPV_VR_OS/app/src/main/cpp/GLRenderer/GLRStereoDaydream.cpp:5:
In file included from /home/build/git/FPV_VR_OS/app/src/main/cpp/GLRenderer/GLRStereoDaydream.h:10:
/home/build/git/Telemetry/TelemetryCore/src/main/cpp/TelemetryReceiver/TelemetryReceiver.h:17:10: fatal error: 'SettingsN.hpp' file not found
```

**Comment by Consti10** [comment]
Hi, I have updated all 4 repos, they should now build on master branch.
The new ndk prefab hopefully makes these compilation issues obsolete but it is only in canary yet.

**Comment by muzy** [comment]
Hi, thank you for updating the repositories. I've just verified that the build finishes successfully. Thank you for your quick response and great work!
